const data = {
  products: [
    {
      name: 'Camo Down Vest',
      slug: 'camo-down-vest',
      category: 'Shirts',
      image: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Floral T-shirt',
      slug: 'floral-t-shirt',
      category: 'Shirts',
      image: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'B&W Longsleeve',
      slug: 'black-white-longsleeve',
      category: 'Shirts',
      image: 'https://i.ibb.co/55z32tw/long-sleeve.png',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pink T-shirt',
      slug: 'pink-t-shirt',
      category: 'Pants',
      image: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Jean Long Sleeve',
      slug: 'jean-long-sleeve',
      category: 'Pants',
      image: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Burgundy T-shirt',
      slug: 'burgundy-t-shirt',
      category: 'Pants',
      image: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;
